### ISSUE TITLE
I would love to contribute, could you share prototype or mock ups?

### ISSUE THREAD

**Issue by salemalem** [linuxmint/website-wizixo#1]

**Comment by tuliocll** [comment]
I want to contribute too, I love linux mint and this will be so fun 🥳

**Comment by clefebvre** [comment]
Hi, thanks for helping out. 

I'm currently working on the main page in wizixo/template/mint-main.html. Don't hesitate to give me feedback.

You can run the website locally simply by cloning this with git locally and then opening `wizixo/template/mint-main.html` in your browser.

**Comment by tuliocll** [comment]
> Hi, thanks for helping out.
> 
> I'm currently working on the main page in wizixo/template/mint-main.html. Don't hesitate to give me feedback.
> 
> You can run the website locally simply by cloning this with git locally and then opening `wizixo/template/mint-main.html` in your browser.

Hi, I open issues or can I send PRs ? I Found a responsivity bug and some accessibility bugs

**Comment by isaacpontes** [comment]
I would love to help too! Looking forward for instructions on how to contribute to the project.

**Comment by clefebvre** [comment]
Yes, issues and PR are welcome.

**Comment by salemalem** [comment]
> > Hi, thanks for helping out.
> > I'm currently working on the main page in wizixo/template/mint-main.html. Don't hesitate to give me feedback.
> > You can run the website locally simply by cloning this with git locally and then opening `wizixo/template/mint-main.html` in your browser.
> 
> Hi, I open issues or can I send PRs ? I Found a responsivity bug and some accessibility bugs
> ![image](https://user-images.githubusercontent.com/22357579/127740638-1dc60508-21de-4a5b-a523-8b3b8d1cbb80.png)

Can you clear cache and hard restart or try in incognito mode? This is the ready Bootstrap template that @clefebvre bought. He didn't code from scratch.

**Comment by tuliocll** [comment]
> Can you clear cache and hard restart or try in incognito mode? This is the ready Bootstrap template that @clefebvre bought. He didn't code from scratch.

I checked it.
On original template its dont happen: 
https://wizixo.webestica.com/index-5.html

**Comment by salemalem** [comment]
> > Can you clear cache and hard restart or try in incognito mode? This is the ready Bootstrap template that @clefebvre bought. He didn't code from scratch.
> 
> I checked it.
> On original template its dont happen:
> https://wizixo.webestica.com/index-5.html

![image](https://user-images.githubusercontent.com/42411937/127746058-63dcb265-1e1d-4074-aa81-572b5bd510d2.png)

**Comment by tuliocll** [comment]
> > > Can you clear cache and hard restart or try in incognito mode? This is the ready Bootstrap template that @clefebvre bought. He didn't code from scratch.
> > 
> > 
> > I checked it.
> > On original template its dont happen:
> > https://wizixo.webestica.com/index-5.html
> 
> ![image](https://user-images.githubusercontent.com/42411937/127746058-63dcb265-1e1d-4074-aa81-572b5bd510d2.png)

You need to clone and test the @clefebvre project:
> You can run the website locally simply by cloning this with git locally and then opening wizixo/template/mint-main.html in your browser.

**Comment by salemalem** [comment]
> > > > Can you clear cache and hard restart or try in incognito mode? This is the ready Bootstrap template that @clefebvre bought. He didn't code from scratch.
> > > 
> > > 
> > > I checked it.
> > > On original template its dont happen:
> > > https://wizixo.webestica.com/index-5.html
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/42411937/127746058-63dcb265-1e1d-4074-aa81-572b5bd510d2.png)
> 
> You need to clone and test the @clefebvre project:
> 
> > You can run the website locally simply by cloning this with git locally and then opening wizixo/template/mint-main.html in your browser.

![image](https://user-images.githubusercontent.com/42411937/127746272-1d8c4752-c829-4c3f-8b95-c113aca543b7.png)

I see bro

**Comment by clefebvre** [comment]
How do you reproduce the issue? I'm using Firefox here and it's working fine.

![image](https://user-images.githubusercontent.com/1138515/127748024-ddd10d27-978a-4a0d-8701-3e288373ca01.png)

**Comment by rmtux** [comment]
It's a glitch in Dev Tools. Try scroll down and once sticky header loads page looks fine. Try and check it using Firefox (see below)
![Screenshot_20210731_214727](https://user-images.githubusercontent.com/32412175/127749711-d95b2a08-7988-4a22-9589-d6db55258c93.png)

**Comment by rmtux** [comment]
I checked against different break points and looks good.
![file_home_rami_Web-Dev_test_website-wizixo-master_wizixo_template_mint-main html all panes 2021-07-31 18 35 09](https://user-images.githubusercontent.com/32412175/127749779-415345a8-4c61-4b7b-86c4-47658a2976ea.png)

**Comment by tuliocll** [comment]
On firefox too (try to scroll to right):
![image](https://user-images.githubusercontent.com/22357579/127752211-29202892-1bcb-47a5-9c52-b5cb07ad34ff.png)

**Comment by tuliocll** [comment]
#4

**Comment by alok1929** [comment]
Hey ,I would also like to help and contribute , is it okay if I use tailwind css , a framework ,to do the css part .It is way faster and has a lot of features 
Do let me know

**Comment by salemalem** [comment]
> Hey ,I would also like to help and contribute , is it okay if I use tailwind css , a framework ,to do the css part .It is way faster and has a lot of features
> Do let me know

Actually, @clefebvre wants to stick with this template, however, he is open to any mock-ups as he mentioned in the Slack channel. (Static site generators are welcome too)

**Comment by alok1929** [comment]
@salemalem , I don't think there is anything written about how to start contributing to this project , I found out its done by cloning the repo and   then opening wizixo/template/mint-main.html in your browser. If its okay , I could add this to the readme.md so its easier for newcomers who want to contribute
Let me know.

**Comment by salemalem** [comment]
Yes, you could add README.md or CONTRIBUTING.md
Or you could propose what changes you want to apply to Clement

**Comment by alok1929** [comment]
Oh so just doing the changes and creating a pull request is enough right ? Okay then

**Comment by salemalem** [comment]
> Oh so just doing the changes and creating a pull request is enough right ? Okay then
Exactly! @alok1929
