### ISSUE TITLE
template/img/logo.svg and logo-mono.svg are made of Ubuntu font... Convert to path to ensure compatibility

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/website-wizixo#12]
The names for these logos are made of text, with the Ubuntu font. Nice, but this will only work on Linux computers ! Am i right ?

I think these "linuxmint" texts should be converted to path, to get a constant look on all computers. But this origin text could still be kept on a separate, hidden layer, in case you want to edit it later. I am working on this now. I will make a pull request soon:

* wizixo/template/img/favicon.ico (new and corrected version)
* wizixo/template/img/logo.svg (current version, text converted to path)
* wizixo/template/img/logo-mono.svg (current version, text converted to path)
* wizixo/template/img/logo2-name.svg (new version, text converted to path)
* wizixo/template/img/logo2-name-green.svg (new version, text converted to path)
* wizixo/template/img/logo2-name-mono.svg (new version, text converted to path)

![logo2-name-green](https://user-images.githubusercontent.com/31940713/127804260-c7a2dd28-449f-48db-ae97-a0dda17e439f.png)

**Comment by Secret-chest** [comment]
The official logo dosen't have that long L!!!

**Comment by SebastJava** [comment]
@Secret-chest 
> The official logo dosen't have that long L!!!

I know. I will make a PR with both the standard version, and my new version here. I prefer this new one, with the long L, but you will get to choose it or not. You can see this in my list up there ▲. Both current versions and new versions will be there. And they all need this text to be converted to path, as far as i can understand.

Here, check this screenshot. I just restarted on Windows 10 to confirm how it is handled there: BAD ! This Ubuntu font got substituted with some Serif font !

![Windows10-mint-main-screenshot](https://user-images.githubusercontent.com/31940713/127866674-968cef44-63e9-4d78-9cd5-38560b64e342.png)

Method used for this test: simple. I simply downloaded and extracted the whole thing in Windows, and opened mint-main in Firefox...

**Comment by UtopicUnicorns** [comment]
You have to import the font via css

**Comment by SebastJava** [comment]
> You have to import the font via css

That is another valid option. But this is just for one word: "linuxmint". So, i converted to path. It should be "rock solid". And simple.

Pull request: https://github.com/linuxmint/website-wizixo/pull/15
