### ISSUE TITLE
Admin/Mods/members

### ISSUE THREAD

**Issue by imsamimalik** [linuxmint/website-wizixo#16]
Why are not the Admin/Mods/members responding to PR or issues? How is this gonna work out?

**Comment by clefebvre** [comment]
They are, it takes time. We also talk on the slack. I can't invite you because your email is not visible on your profile.

**Comment by imsamimalik** [comment]
I do have. it's imsamimalikk@gmail.com it would be my pleasure.

**Comment by imsamimalik** [comment]
@clefebvre
