### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by BhavikJain07** [linuxmint/website-wizixo#18]
Running the current version in the python http.server does not load the css or scss.

**Comment by tuliocll** [comment]
> Running the current version in the python http.server does not load the css or scss.

can you add more infos (logs, prints..) ?
here is working fine:
![image](https://user-images.githubusercontent.com/22357579/128011879-aaf80a8e-ffbb-46dc-b040-4bdd64042a5c.png)

are you on the right folder ?

**Comment by BhavikJain07** [comment]
There is no mint-main.html file in the template folder. There is only mint-page-main.html and opening that in the python server does not load css. ![Screenshot_20210803-181201.png](https://user-images.githubusercontent.com/55630138/128017329-4dc9a57a-c0b8-4990-9855-53eecd95e58e.png)

**Comment by tuliocll** [comment]
> There is no mint-main.html file in the template folder. There is only mint-page-main.html and opening that in the python server does not load css. ![Screenshot_20210803-181201.png](https://user-images.githubusercontent.com/55630138/128017329-4dc9a57a-c0b8-4990-9855-53eecd95e58e.png)

you need to run the `build.py` script, then start the http server.

**Comment by BhavikJain07** [comment]
Thanks for the help. I guess we can now close this issue.
