### ISSUE TITLE
Drop down menu goes outside page.

### ISSUE THREAD

**Issue by fredcw** [linuxmint/website-wizixo#20]
At some browser window sizes the rightmost drop down menu extends past the window edge:
![Screenshot from 2021-08-03 13-37-32](https://user-images.githubusercontent.com/58893963/128017262-c15fa2b0-f096-4385-aaf4-29a5237ad3c7.png)

**Comment by tuliocll** [comment]
> At some browser window sizes the rightmost drop down menu extends past the window edge:
> ![Screenshot from 2021-08-03 13-37-32](https://user-images.githubusercontent.com/58893963/128017262-c15fa2b0-f096-4385-aaf4-29a5237ad3c7.png)

call you make a pull, a PR was marged to fix this #4

**Comment by tuliocll** [comment]
sorry, its still happing, I put the wrong width value 😅
I created a new PR #21
