### ISSUE TITLE
A different background?

### ISSUE THREAD

**Issue by fredcw** [linuxmint/website-wizixo#25]
I think the wallpaper Telento-2 from Mint 9 (Isadora) makes a good background picture:

![Screenshot from 2021-08-04 08-22-31](https://user-images.githubusercontent.com/58893963/128139841-902e303b-8ea5-4765-a796-ec14f0f9c7a4.jpg)

I just replaced the file `website-wizixo/wizixo/template/assets/images/bg/pattern/02.png`

**Comment by IdrisTheDragon** [comment]
It does make a good background, but the readability of the white text and the Logo start to get a bit lost.

**Comment by fredcw** [comment]
Here's a cropped version of Talento-1.jpg:

![Screenshot from 2021-08-04 09-50-49](https://user-images.githubusercontent.com/58893963/128152489-e2118297-8b76-4786-b3b1-cc49e178770f.jpg)

**Comment by clefebvre** [comment]
This reminds me of Mint 9 Gloria :) 

I like it, but I'd rather stick with the gradient artwork provided by the theme. If we change the colors in the SCSS we get it all regenerated. It matches content and action boxes, buttons etc.. also.
