### ISSUE TITLE
New website mixed up with all the template code.

### ISSUE THREAD

**Issue by IdrisTheDragon** [linuxmint/website-wizixo#3]
The new website code is all mixed in with the template code. Suggest separating them, leaving template intact for reference... I've started to separate them, but am a bit busy atm so unlikely to finish:

https://github.com/IdrisTheDragon/website-wizixo

Done:
- Setup separate project environment
- Move linux mint website page to new directory
- Bulk copy assets over to new location

TODO:
- Clean up `linuxmint/assets/*` of unnecessary template assets
- Clean up `wizixo/*` of linux mint content.

**Comment by SebastJava** [comment]
Yes, doing such a separation sounds like a good idea. At first. I don't know. But at least, as a minimum, it surely would be good to mention on the README.md that the page we are looking for is: `wizixo/template/mint-main.html` That's it for now. We are only looking at the landing page.

**Comment by IdrisTheDragon** [comment]
Doing a full separation from the start will save work later on when trying to untangle unused template code. Even if just looking at the landing page atm, it will still have dependencies in other files. Knowing exactly what those are would be useful later down the line when developing more pages.

Also potentially need to consider the licensing of the paid for template. Does the license allow us to make it's template publicly visible like this. It may need to be removed. Which would be much easier if it is separate from our code.

**Comment by IdrisTheDragon** [comment]
Thinking of my second point, after a quick browse:

https://themes.getbootstrap.com/product/wizixo-multipurpose-corporate-theme/

https://themes.getbootstrap.com/licenses/#fullStandardLicense

Drawing attention to point 4.2 of the templates licenses:

`You cannot Re-distribute the Theme’s source, modified or not, even if the Theme is modified.`

Point 4.4 may also be applicable.

So may need to remove the template code other than what is used for the linuxmint website sooner rather than later. As currently the repository could be considered as redistributing a modified version of the template, due to it mostly being the template.

*Note: I am no expert on licensing so probably missed something but thought it was worth drawing attention to it.

**Comment by HEXcube** [comment]
Licensing issue could be solved, in one of these 2 ways:

1. Contact the template creators and obtain an exception or permission to allow relicensing under more open-source compatible and community-friendly licenses. That'll make sure other open-source licensed components may be added to the website later if and when needed.
2. If relicensing or exception isn't an option, it's better to convert the repo to a closed one that's not publicly accessible. Only the core contributors would get direct access to the repo. I dunno how that'll benefit a community-driven project like this in the long-term though. 😕

**Comment by Secret-chest** [comment]
> Licensing issue could be solved, in one of these 2 ways:
> 
> 1. Contact the template creators and obtain an exception or permission to allow relicensing under more open-source compatible and community-friendly licenses. That'll make sure other open-source licensed components may be added to the website later if and when needed.
> 2. If relicensing or exception isn't an option, it's better to convert the repo to a closed one that's not publicly accessible. Only the core contributors would get direct access to the repo. I dunno how that'll benefit a community-driven project like this in the long-term though. 😕 

@HEXcube 
3. Make the website from scratch, it will also look more unique

**Comment by HEXcube** [comment]
> 3. Make the website from scratch, it will also look more unique

Yeah, that's an option too, provided it's possible to discard all this current work and start over again. If that's the case, I'd suggest building on top of a more liberally licensed template, than building the whole thing from scratch. It seems to be a more practical method. But then again, if there are enough contributors up for building from scratch, it might be viable.

**Comment by Secret-chest** [comment]
> > 1. Make the website from scratch, it will also look more unique
> 
> Yeah, that's an option too, provided it's possible to discard all this current work and start over again. If that's the case, I'd suggest building on top of a more liberally licensed template, than building the whole thing from scratch. It seems to be a more practical method. But then again, if there are enough contributors up for building from scratch, it might be viable.

Or using plain bootstrap with CSS

**Comment by SebastJava** [comment]
I guess it would be faster and easier if you could just keep going with this **Wizixo**. Clem would likely prefer this... But if you are to restart all over again, then of course it would be much better to go with **Bootstrap**. Otherwise, it gets very complicated when you get into responsive design...

https://www.w3schools.com/bootstrap/bootstrap_ver.asp

**Comment by atTheShikhar** [comment]
Probably i'm a little late to join here, but making the website from scratch sounds a great idea. Since we are only going to use static pages, html along with pure css ( or scss for that matter ) is a great solution. Using a template will result in useless boilerplate code (which may result in slower loading speed) and also will make the website look less original. 

Speaking of responsive , this project (redesigning part) is still in it's initial phase and many front end developers just began to come in to contribute. I myself can do responsive design without using bootstrap and i'm pretty sure any front end guy who have earlier worked with css can do it aswell.

**Comment by Secret-chest** [comment]
> Probably i'm a little late to join here, but making the website from scratch sounds a great idea. Since we are only going to use static pages, html along with pure css ( or scss for that matter ) is a great solution. Using a template will result in useless boilerplate code (which may result in slower loading speed) and also will make the website look less original.
> 
> Speaking of responsive , this project (redesigning part) is still in it's initial phase and many front end developers just began to come in to contribute. I myself can do responsive design without using bootstrap and i'm pretty sure any front end guy who have earlier worked with css can do it aswell. 
> 
> Also if we go with pure css, we will have the full control over our design, designers only need to give the mockups and that can be implemented exactly as the webpage

@HEXcube @clefebvre @atTheShikhar I can code HTML/CSS

**Comment by clefebvre** [comment]
I'll close this since we solved it in the slack. We're not redistributing even though this repo is public. I'll remove the zip and gradually remove assets we don't need. The reason it's public is because we're still forming the team.

Separation is done to some extent. template/ will become the www root eventually. Our own assets are in img/ and css/, what's in assets is what's from the theme.

**Comment by clefebvre** [comment]
@Secret-chest send us an email at root@linuxmint.com so we can send you an invite.
