### ISSUE TITLE
License - is the theme free and open-source?

### ISSUE THREAD

**Issue by MikkCZ** [linuxmint/website-wizixo#47]
Hi.

I noticed you are building the new website based on Wizixo - a commercial website theme. I started looking at the template and following the pages
- from https://wizixo.webestica.com/
- https://www.webestica.com/
- https://themes.getbootstrap.com/store/webestica/
- https://themes.getbootstrap.com/product/wizixo-multipurpose-corporate-theme/
- to https://themes.getbootstrap.com/licenses/

I found the last page says for all three licenses:

> 4. You cannot… 
>>  2. Re-distribute the Theme’s source, modified or not, even if the Theme is modified.

Did you actually obtain another license, that allows you to publish it here and subsequently Linux Mint communities to use the Wizixo theme and your modifications as if it would be free and open-source?

**Comment by clefebvre** [comment]
No, the license is only for us to build the Mint website.
