### ISSUE TITLE
New logo suggestion

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/website-wizixo#48]
I haven't created a PR for this as I don't know if you like it... But I think the circle shape isn't minty at all, but the old logo is too detailed. So I decided to make a crossover of both. I used the official LM shape extracted from the badge logo for this, so the LM is right.
Now, let me show you the logo. _sorry but I had to use PNG_
![linuxmint-icon](https://user-images.githubusercontent.com/74449186/129920173-101640d8-8fe0-4cfc-94f8-5804ad470744.png)
The shape is a leaf, but it no does not has a stem to prevent the logo from being offcenter, and also make the shape more symetrical. It is more rounded than the old logo, to make it look more like a leaf. The logo now has 2 colors (without a gradient), which are less limy and more minty. I used 2 colors to give the logo some depth. The colors are ![#4caf50](https://img.shields.io/badge/-%234caf50-%234caf50?style=flat-square) and ![#4caf50](https://img.shields.io/badge/-%23388e3c-%23388e3c?style=flat-square) The color for the LM is ![#4caf50](https://img.shields.io/badge/-%23fafafa-%23fafafa?style=flat-square).

**Comment by Secret-chest** [comment]
I will make a repo for this to add SVG.

**Comment by Secret-chest** [comment]
Done. Secret-chest/linuxmint-logo

**Comment by clefebvre** [comment]
@Secret-chest don't hesitate to use the slack for this (logo channel) as it's not related to the website project.

Personally my priority is to go ahead with the new website also and not to be distracted with a logo change at this time. I'm not saying we'll never change the logo ever again, but I don't think we should do so in the near future.

**Comment by Secret-chest** [comment]
@clefebvre Just so you know, people like the logo. See here: https://forums.linuxmint.com/viewtopic.php?f=19&t=355555
