### ISSUE TITLE
A modern homepage redesign concept

### ISSUE THREAD

**Issue by parasshah195** [linuxmint/website-wizixo#51]
Linux Mint deserves more than a cookie-cutter template. Here's my take on the Linux Mint homepage redesign:

![Linux Mint Home Concept](https://user-images.githubusercontent.com/18551588/131485972-ca5cba65-49ef-4441-bb1a-e76c5584065e.png)

The aim was to preserve the original feel of the existing website - the fresh tea green. The content and hierarchy was inspired from the latest version here as of a day before posting this issue.

The prototype preview of the concept can be viewed in the browser [here](https://www.figma.com/proto/bfEHy6InUzSLBblReVcNzG/linuxmint.com-redesign?page-id=0%3A1&node-id=19%3A2&viewport=0%2C48%2C0.11&scaling=scale-down-width).

What do you think?

**Comment by clefebvre** [comment]
I like it.

We're almost ready to deploy the wizixo version though and we've got all the elements we need to deploy it successfully. This in comparison is only a design and it would mean starting again from scratch.

I'm interested in continuing to explore new ideas like this one in the future and maybe one day replace the wizixo one, but for now we're going forward with the wizixo.
