### ISSUE TITLE
Goodbye

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/website-wizixo#52]
I can't help with anything. I am very sad that you chose to buy a template. If you can't make the website from scratch, someone like me can.

**Comment by Secret-chest** [comment]
So I won't do anything here anymore, as it will get rejected anyways.

**Comment by clefebvre** [comment]
That's not productive or helpful.

With this template we have a chance to finally get something done, this is what this project is about. If you're not interested in it, don't join it.

We're also open to alternatives long term but that's outside of the scope here. If you can indeed make something better from scratch, by all means do. Don't prevent us from finishing this in the meantime while we've no alternatives.
