### ISSUE TITLE
font awesome, yuck

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/website-wizixo#6]
I think you should change fa icons to Material icons, Font Awesome icons always look strange. I might also do this myself.

**Comment by HEXcube** [comment]
That's coz the current icons are Font Awesome 4, as you can see from the scss file:

[See current font-awesome.scss](https://github.com/linuxmint/website-wizixo/blob/c91391c5956dae4aed49c4dc7f352fb5d6b9c321/wizixo/template/assets/vendor/font-awesome/scss/font-awesome.scss)

I think upgrading to [Font Awesome 5](https://fontawesome.com) would be a good solution too. I addition, using the SVG based icons from Font Awesome 5 could help add [animation and customization](https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/layering), if needed.

**Comment by HEXcube** [comment]
Another thing to keep in mind while choosing icons is the license. Font Awesome 5's SVG icons are CC BY 4.0 : https://fontawesome.com/license/free , while Material Icons are Apache 2.0 : https://google.github.io/material-design-icons/#licensing . It would be better to pick the one that's more compatible with the current project.

**Comment by clefebvre** [comment]
Can you show us a before/after comparison?

**Comment by thevipinmishra** [comment]
Why aren't we using official Bootstrap Icons?

https://icons.getbootstrap.com/

It got a decent collection and we can always go for SVG icons in case a particular icon isn't available in the Bootstrap Icons.

**Comment by Secret-chest** [comment]
> We're pointing to the latest FA at the moment. I think they look nice, but if other sets look better I'm happy to consider them.
> 
> The licenses are fine imo.

@clefebvre Okay. Material Icons are very consistent and balanced. They don't have social logos but we might add these with SVG. [fonts.google.com/icons]()
