### ISSUE TITLE
A generic Template for pages

### ISSUE THREAD

**Issue by imsamimalik** [linuxmint/website-wizixo#7]
I think a generic template for all pages should be provided like a simplest page which includes basic elements like header, footer etc. Because now header is still in progress and any changes made would have to be copied to every other page.

**Comment by crydotsnake** [comment]
Yep, good idea. Its like a snippet then.

**Comment by kharbanda14** [comment]
currently it's html, should we switch to template engines (like handlebars) and integrate with gulp ?

**Comment by crydotsnake** [comment]
Sure, why not.

What do you mean, integrate with gulp?

**Comment by kharbanda14** [comment]
cool, i think we need to add a new task something similiar to the compling .scss files with sass in the **gulpfile.js**, I will be checking some code examples and documentation.

**Comment by horberlan** [comment]
can I do the front-end with animation on bg

**Comment by clefebvre** [comment]
We now have sections for header, footer and title and the ability to include sections in any page.
