### ISSUE TITLE
Can't setup gulp and install npm modules!

### ISSUE THREAD

**Issue by thevipinmishra** [linuxmint/website-wizixo#9]
I globally installed gulp and after that I hit `npm install ` and it throws an error!

I really want to contribute, but can't because of this :(

![Error](https://user-images.githubusercontent.com/52159805/127777642-2b5621a1-d045-4131-906d-655bc4a5fe46.png)

Please help!

**Comment by crydotsnake** [comment]
Do you have the latest NodeJS Version?

**Comment by kharbanda14** [comment]
as per the minimum requirements, for v4.14.1 you need node js v14, you can refer the following link 
https://www.npmjs.com/package/node-sass/v/4.14.1

**Comment by thevipinmishra** [comment]
Hey @crydotsnake & @kharbanda14 

I am a web dev and my setups are very often updated, Its 16.4.2 on my machine currently, and latest lts version of Node is 16.6.0

So It's more than enough I think?

**Comment by crydotsnake** [comment]
Or you can use nvm (node version manager) to switch between nodejs versions.

**Comment by thevipinmishra** [comment]
@crydotsnake, Hi, I already havenvm, which npm version will do the task smoothly?

Any help?

**Comment by crydotsnake** [comment]
Try it with version: v11.15.0

**Comment by thevipinmishra** [comment]
I don't know why am I not getting rid of this :(

Can someone please add some instructions on how to set up the project properly and what are the minimum dependencies?

It will be a great help!

![image](https://user-images.githubusercontent.com/52159805/127805388-f0922f22-b403-4cd2-9b43-ae781692a63d.png)

**Comment by tuliocll** [comment]
> I don't know why am I not getting rid of this :(
> 
> Can someone please add some instructions on how to set up the project properly and what are the minimum dependencies?
> 
> It will be a great help!
> 
> ![image](https://user-images.githubusercontent.com/52159805/127805388-f0922f22-b403-4cd2-9b43-ae781692a63d.png)

Send the full error log.
You can try this:
```sh
npm rebuild node-sass
```

Below is a quick guide for minimum and maximum support supported version of node-sass:
![image](https://user-images.githubusercontent.com/22357579/127862578-8f5098ba-da4a-40c7-8f5f-c3303f6edf43.png)

try to use nodejs 14, too (i using 15.9.0)
![image](https://user-images.githubusercontent.com/22357579/127862806-44d0df06-a9ce-4350-a91c-62c810c05bac.png)

**Comment by atTheShikhar** [comment]
> I globally installed gulp and after that I hit `npm install ` and it throws an error!
> 
> I really want to contribute, but can't because of this :(
> 
> ![Error](https://user-images.githubusercontent.com/52159805/127777642-2b5621a1-d045-4131-906d-655bc4a5fe46.png)
> 
> Please help!

Try uninstalling gulp from you global packages and then run npm install on this project's root directory. Global installs cause problems sometimes.

You can reference [this](https://www.smashingmagazine.com/2016/01/issue-with-global-node-npm-packages/) article.

**Comment by thevipinmishra** [comment]
I think I am done here. Tried every latest node and npm, tried older ones as well. Uninstalled global instance of gulp, nothing worked here.

We could have gone simpler with the setup.

**Comment by tuliocll** [comment]
> I think I am done here. Tried every latest node and npm, tried older ones as well. Uninstalled global instance of gulp, nothing worked here.
> 
> We could have gone simpler with the setup.
> 
> I am doing this on Linux here, LInux Mint to be specific.

Please, post the full log of this command:

```bash
node -v && npm install
```

**Comment by clefebvre** [comment]
You only need gulp if you want to work on the theme by the way... i.e. if you want to modify the SCSS and regenerate the assets. For anything else, a text editor, a terminal and a browser is enough.

Regarding gulp, I'm using the repository one personally.

**Comment by thevipinmishra** [comment]
@clefebvre Ofcourse I want to customize the theme itself and not the compiled src so that everything can stay synced with source.

Will do this log thing tomorrow.

**Comment by whelmich** [comment]
To make sass work with node 16.2, I updated the dependencies in package.json:

```   
"gulp": "^4.0.2",
"gulp-sass": "^5.0.0",
"node-sass": "^6.0.1"
```
Also the sass import had to change in gulpfile.js line 4:
`var sass = require('gulp-sass')(require('node-sass'));`

**Comment by thevipinmishra** [comment]
@whelmich, You are a lifesaver!!

Thanks a lot. It works perfectly now, without any warnings or errors.

I made the changes as you suggested and it runs perfectly.

Thanks a lot again!
